### ISSUE TITLE
对于网站的一些问题与建议

### ISSUE THREAD

**Issue by Luna-Grace** [hs3434/hs3434.github.io#1]
*[知乎](https://www.zhihu.com/question/581691050/answer/3529511456)上看到的链接*  

1. 可以在仓库侧边栏添加GitHub Page链接
2. 在网站中使用`F12`打开开发工具时会弹出“请遵守GPL协议”的提示，但仓库中没有对应的LICENSE。
![image](https://github.com/user-attachments/assets/c17da75a-6b84-4d78-ac54-699b7f5c750c)
3. 在点击右下角的版权示意图标后跳转到的页面是404
> 这个图标:
> ![image](https://github.com/user-attachments/assets/fdd810c0-f78c-4354-9a58-377a502e6726)

**Comment by hs3434** [comment]
感谢给出改进意见，
1、 加了github图标
2、 仓库是使用hexo一键部署的，默认没有证书。以后有空看看怎么加。
3、 这个链接忘记加，已经加了




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hs3434/hs3434.github.io"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月5日(星期一) 凌晨3:17
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[hs3434/hs3434.github.io] 对于网站的一些问题与建议 (Issue #1)





 
知乎上看到的链接
  
可以在仓库侧边栏添加GitHub Page链接
 
在网站中使用F12打开开发工具时会弹出“请遵守GPL协议”的提示，但仓库中没有对应的LICENSE。
 image.png (view on web)
 
在点击右下角的版权示意图标后跳转到的页面是404
   
这个图标:
 image.png (view on web)
